### ISSUE TITLE
Changes/fixes ?

### ISSUE THREAD

**Issue by SGZ-Creations** [H4ckerxx44/Darkstar-Utilities-Fixed#1]
what is changed/fixed in this one compared to the default mod ?

**Comment by H4ckerxx44** [comment]
Well, seems like I did not include that in the Changelog.

I mainly fixed typos and some "Missing Key" stuff in the game cause it was bothering me, nothing feature wise.

**Comment by H4ckerxx44** [comment]
I released a new update with a changelog.

**Comment by SGZ-Creations** [comment]
Ty.
