### ISSUE TITLE
Vehicles dont work with AAI Industry 

### ISSUE THREAD

**Issue by DidgetMidget** [H4ckerxx44/Darkstar-Utilities-Fixed#11]
It would be awesome if the vehicles work with AAI Industry especially the Deep Hold. 

At the moment they are able to turn with the AI enabled but they dont move forward (i guess because they are flying?)

**Comment by SGZ-Creations** [comment]
Won't do as aai and SE had marked original mod incompatible.

Amd would be hard to do. Reason is that AAI mod is doing wonky stuff to other mods
