### ISSUE TITLE
"Optimisation Science Pack" do not work with the space exploration mod

### ISSUE THREAD

**Issue by DidgetMidget** [H4ckerxx44/Darkstar-Utilities-Fixed#12]
Darkstar adds something called a "lanari station" where you are able to produce those science packs.

The science packs are really important for bot research (speed capacity) and other optimisations 

But that research is completely bonkers 

![image](https://user-images.githubusercontent.com/54773103/167433010-ea3f396e-0c44-4024-ad5b-4fa6fa205a52.png)
As you can see Linari Sation comes before the moon station but u need the moon one for the linari one 

![image](https://user-images.githubusercontent.com/54773103/167433161-de709d4b-54fc-4037-b9fa-171a9728b1ee.png)
You need those 2 items for the linari one 

![image](https://user-images.githubusercontent.com/54773103/167433230-b85da563-8478-466a-b2ad-89ed94793a1b.png)
And you unlock them with the moon station but you need the utility packs for that unlock 

So there is no way to get the moon one and by that no means of getting the optimisation science pack

swapping those research should do the trick

![image](https://user-images.githubusercontent.com/54773103/167435069-b599f5d1-7982-4732-9fc0-6ad56e435e4a.png)
There are those 2 station located in the tehcnology.lua at line 4200 you can see that spacestation 1 comes before the moon one

**Comment by H4ckerxx44** [comment]
The thing is, the original Darkstar Utilities mod has never finished these space stations.
I have fixed some missing translations keys about them but even indicating by their description, this is all unfinished

**Comment by DidgetMidget** [comment]
I tried all those stations out in a world they seem to work just fine you can launch stuff into space get your stuff to build those research data servers only thing thats missing a better item description (maybe did the original autor envision those stations to be anything else then just stuff u shoot into space but its functional atm)

![image](https://user-images.githubusercontent.com/54773103/167511428-0fb61187-6773-40e7-bb1d-e2b48a002b41.png)
okay one small issue you can rotate them and they got no texture for that

i think their functionallity is completly implemented just not the design and sound (got a basic mining drill sound atm)

**Comment by SGZ-Creations** [comment]
new info about darkstar and SE won't be fixes as latest news causes the 2 to crash.
