### ISSUE TITLE
Processed Fuel from AAI

### ISSUE THREAD

**Issue by totallynotastudent** [H4ckerxx44/Darkstar-Utilities-Fixed#13]
Brick Furnaces can't use the Processed fuel from AAI
![image](https://user-images.githubusercontent.com/44736630/188271429-fee22469-ac20-4360-9f26-1566412ef18a.png)

**Comment by SGZ-Creations** [comment]
Please confirm this is the case with other furnaces too.

**Comment by SGZ-Creations** [comment]
SE And Darkstar crashes and it will be a seamless crashing loop to try fixing. and 2.0 is close anyway.
