### ISSUE TITLE
Compatibility with 248K 

### ISSUE THREAD

**Issue by SGZ-Creations** [H4ckerxx44/Darkstar-Utilities-Fixed#14]
Hey i solved a compatibility issue with 248K & Darkstar by renaming "lithium-ore" to "dark-lithium-ore" and it solved issue with the ore not being obtainable. 

not able to fix spawning.

**Comment by H4ckerxx44** [comment]
That's awesome! Mind making a PR so I can update it?

Meanwhile I thought about prefixing _all_ items with `ds-`, not sure how that would break existing saves though...

**Comment by SGZ-Creations** [comment]
If u rename make sure to add the old and new names in a migration setup that should not break anything

**Comment by SGZ-Creations** [comment]
Have made the fix I'm not really good with Pushing the fix to u as the GitHub is new still to me.

**Comment by SGZ-Creations** [comment]
https://github.com/SGZ-Creations/Darkstar-Utilities-Fixed-0.19.13/compare/main%40%7B1day%7D...main

**Comment by SGZ-Creations** [comment]
https://github.com/SGZ-Creations/Darkstar-Utilities-Fixed-0.19.13 if u can access it

**Comment by H4ckerxx44** [comment]
Do you fully want to take over the Darkstar utilities for your own maintenance? @SGZ-Creations 

If you are down for it, I can help you set up everything as it should be set up, add me on discord under `@d4nn1s`

**Comment by SGZ-Creations** [comment]
I will only have published on git not portal. Tho if u allow me to upload under your post sure I don't mind.

**Comment by H4ckerxx44** [comment]
I have trouble understanding what you mean, you surely can link your repo below here, yeah.

My question is if you plan to maintain Darkstar Utilities from now on cause I simply can't. If so, I would make some links and set up things to redirect anything to your GitHub repo & Factorio Mod page

It would be easier to quickly talk on discord :D

**Comment by SGZ-Creations** [comment]
I can take care of the mod for now. Also chat on discord.
